// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace vteCore.dbBFA.Models;

[Keyless]
public partial class dfa_view
{
    public string StctNo { get; set; }

    public string HSISType { get; set; }

    public string Council1 { get; set; }

    public string Location { get; set; }

    public string InitType { get; set; }

    public string FacilityProvision { get; set; }

    public string Status { get; set; }
}