// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace vteCore.dbBFA.Models;

public partial class DFADoc
{
    [Key]
    public int Id { get; set; }

    public int ModelOrder { get; set; }

    [Required]
    [StringLength(200)]
    public string ManualName { get; set; }

    public string ManualPath { get; set; }

    [StringLength(100)]
    public string FileName { get; set; }

    [StringLength(50)]
    public string GroupBy { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ManualDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime updatedAt { get; set; }

    [StringLength(100)]
    public string updatedBy { get; set; }
}