// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace vteCore.dbBFA.Models;

[Table("DFAMessage")]
public partial class DFAMessage
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string MessageType { get; set; }

    public string Messages { get; set; }

    [Required]
    public string FollowStcNos { get; set; }

    [Required]
    [StringLength(50)]
    public string UserId { get; set; }

    public bool Seen { get; set; }

    public string ReadStcNos { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; }
}