// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace vteCore.dbBFA.Models;

[Table("DFAUserConfig")]
public partial class DFAUserConfig
{
    [Key]
    public int Id { get; set; }

    public int UserKey { get; set; }

    [StringLength(50)]
    public string ExportName { get; set; }

    [StringLength(50)]
    public string ExportType { get; set; }

    public string ExportFields { get; set; }

    [ForeignKey("UserKey")]
    [InverseProperty("DFAUserConfigs")]
    public virtual DFAUser UserKeyNavigation { get; set; }
}