// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace vteCore.dbBFA.Models;

[Keyless]
public partial class setting_view
{
    [Required]
    [StringLength(50)]
    public string SettingId { get; set; }

    [StringLength(1000)]
    public string SettingValue { get; set; }
}