// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace vteCore.dbBFA.Models;

[Table("WalkwayBFARecord")]
public partial class WalkwayBFARecord
{
    [Key]
    public int Id { get; set; }

    public int ImportKey { get; set; }

    [StringLength(50)]
    public string StctNo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TakeDate { get; set; }

    [StringLength(50)]
    public string InitType { get; set; }

    [StringLength(50)]
    public string HSISType { get; set; }

    [StringLength(50)]
    public string ChildType { get; set; }

    [StringLength(50)]
    public string ParentType { get; set; }

    [StringLength(50)]
    public string StctAdjoin { get; set; }

    [StringLength(500)]
    public string Location { get; set; }

    [StringLength(50)]
    public string StairIndp { get; set; }

    [StringLength(50)]
    public string Council1 { get; set; }

    [StringLength(50)]
    public string Council2 { get; set; }

    [StringLength(50)]
    public string InRegion { get; set; }

    public int ExitCnt { get; set; }

    [StringLength(50)]
    public string FacilityProvision { get; set; }

    [StringLength(50)]
    public string WideEnough { get; set; }

    [StringLength(50)]
    public string Gradlt10 { get; set; }

    [StringLength(50)]
    public string WithSteps { get; set; }

    [StringLength(500)]
    public string StepsForBFA { get; set; }

    [StringLength(50)]
    public string AlterMeans { get; set; }

    [StringLength(500)]
    public string AlterDetail { get; set; }

    [StringLength(50)]
    public string AlterDist { get; set; }

    [StringLength(50)]
    public string AtMainForBFA { get; set; }

    [StringLength(500)]
    public string Remarks { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; }

    [StringLength(50)]
    public string UpdatedByPost { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(50)]
    public string EndorsedBy { get; set; }

    [StringLength(50)]
    public string EndorsedByPost { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndorsedAt { get; set; }

    [StringLength(50)]
    public string AuditedBy { get; set; }

    [StringLength(50)]
    public string AuditedByPost { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AuditedAt { get; set; }

    [StringLength(50)]
    public string SnapShotFor { get; set; }

    [StringLength(50)]
    public string SnapShotBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SnapShotAt { get; set; }

    [InverseProperty("BfaRecord")]
    public virtual ICollection<WalkwayBFAExit> WalkwayBFAExits { get; set; } = new List<WalkwayBFAExit>();

    [InverseProperty("BfaRecord")]
    public virtual ICollection<WalkwayBFAVerify> WalkwayBFAVerifies { get; set; } = new List<WalkwayBFAVerify>();

    [InverseProperty("BfaRecord")]
    public virtual ICollection<WalkwayPicRecord> WalkwayPicRecords { get; set; } = new List<WalkwayPicRecord>();
}