// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace vteCore.dbBFA.Models;

[Table("WalkwayPicRecord")]
public partial class WalkwayPicRecord
{
    [Key]
    public int Id { get; set; }

    public int BfaRecordId { get; set; }

    public int? BfaExitId { get; set; }

    [StringLength(50)]
    public string PicType { get; set; }

    public string UploadFilePath { get; set; }

    [StringLength(500)]
    public string BackupRelativePath { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("BfaExitId")]
    [InverseProperty("WalkwayPicRecords")]
    public virtual WalkwayBFAExit BfaExit { get; set; }

    [ForeignKey("BfaRecordId")]
    [InverseProperty("WalkwayPicRecords")]
    public virtual WalkwayBFARecord BfaRecord { get; set; }
}