// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace vteCore.dbBFA.Models;

[Table("WalkwayBFAVerify")]
public partial class WalkwayBFAVerify
{
    [Key]
    public int Id { get; set; }

    public int BfaRecordId { get; set; }

    public int ImportKey { get; set; }

    [StringLength(50)]
    public string InvgORPorUAP { get; set; }

    [StringLength(50)]
    public string InvgStatusORPorUAP { get; set; }

    [StringLength(500)]
    public string InvgRemarksORPorUAP { get; set; }

    [StringLength(100)]
    public string InvgAgreeNo { get; set; }

    [StringLength(50)]
    public string DCInAgreeNo { get; set; }

    [StringLength(50)]
    public string ConnectAdjoin { get; set; }

    [StringLength(50)]
    public string BSInChecked { get; set; }

    [StringLength(50)]
    public string FollowupRegion { get; set; }

    [StringLength(50)]
    public string AuditedBy { get; set; }

    [StringLength(50)]
    public string AuditedByPost { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AuditedAt { get; set; }

    [ForeignKey("BfaRecordId")]
    [InverseProperty("WalkwayBFAVerifies")]
    public virtual WalkwayBFARecord BfaRecord { get; set; }
}