// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace vteCore.dbBFA.Models;

[Table("WalkwayBFAExit")]
public partial class WalkwayBFAExit
{
    [Key]
    public int Id { get; set; }

    public int BfaRecordId { get; set; }

    [StringLength(10)]
    public string ExitNo { get; set; }

    [StringLength(50)]
    public string ExitToBuild { get; set; }

    [StringLength(500)]
    public string AtExitFor { get; set; }

    [StringLength(500)]
    public string ReasonwNoBFA { get; set; }

    [StringLength(500)]
    public string DescwBFA { get; set; }

    [StringLength(500)]
    public string AlterMeanswBFA { get; set; }

    [StringLength(500)]
    public string AlterDetailwBFA { get; set; }

    [StringLength(500)]
    public string AlterDist { get; set; }

    [StringLength(2000)]
    public string Remarks { get; set; }

    [StringLength(50)]
    public string ExitwBFA { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("BfaRecordId")]
    [InverseProperty("WalkwayBFAExits")]
    public virtual WalkwayBFARecord BfaRecord { get; set; }

    [InverseProperty("BfaExit")]
    public virtual ICollection<WalkwayPicRecord> WalkwayPicRecords { get; set; } = new List<WalkwayPicRecord>();
}