import { LinkNameEnum, MenuPositionEnum, RouteInput, TRANSITION_DEFAULT } from '@/constants/types'
import HomeComponent from '@/pages/landing'

const asides: RouteInput[] = [
  {
    Component: HomeComponent,
    name: LinkNameEnum.menu1,
    locked: false,
    path: '/menu1',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.menu2,
    locked: false,
    path: '/menu2',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.submenu1,
    locked: false,
    path: '/submenu1',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.menu2,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.submenu2,
    locked: false,
    path: '/submenu2',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.menu2,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.menu3,
    locked: false,
    path: '/menu3',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.submenu3,
    locked: false,
    path: '/submenu3',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.menu3,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.sub1menu1,
    locked: false,
    path: '/sub1menu1',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.submenu3,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.sub1menu2,
    locked: false,
    path: '/sub1menu2',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.submenu3,
  },

  {
    Component: HomeComponent,
    name: LinkNameEnum.submenu4,
    locked: false,
    path: '/submenu4',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.menu3,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.sub1menu3,
    locked: false,
    path: '/sub1menu3',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.submenu4,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.sub1menu4,
    locked: false,
    path: '/sub1menu4',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.submenu4,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.sub2menu1,
    locked: false,
    path: '/sub2menu1',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.sub1menu4,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.sub2menu2,
    locked: false,
    path: '/sub2menu2',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.sub1menu4,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.sub3menu1,
    locked: false,
    path: '/sub3menu1',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.sub2menu2,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.submenu5,
    locked: false,
    path: '/submenu5',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.menu3,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.submenu6,
    locked: false,
    path: '/submenu6',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.menu3,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.sub1menu5,
    locked: false,
    path: '/sub1menu5',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.submenu6,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.sub1menu6,
    locked: false,
    path: '/sub1menu6',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.submenu6,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.sub1menu7,
    locked: false,
    path: '/sub1menu7',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
    parentName: LinkNameEnum.submenu6,
  },
  {
    Component: HomeComponent,
    name: LinkNameEnum.menu4,
    locked: false,
    path: '/menu4',
    popUpOnly: false,
    position: MenuPositionEnum.aside,
    transition: TRANSITION_DEFAULT,
    iconIndex: 0,
  },
]

export default asides
